### ISSUE TITLE
Flagging 1.X Versions

### ISSUE THREAD

**Issue by theonlykernel** [hillu/local-log4j-vuln-scanner#11]
Is it intended that this utility will flag 1.X versions? It has been stated that "As log4j 1.x does NOT offer a look-up mechanism, it does NOT suffer from CVE-2021-44228". Does this mean that 1.X versions can and should be disregarded?

Thx

**Comment by uschindler** [comment]
I'd recommend to add a command line flag to disable log4j 1.x artifacts.

They are not vulnerable per se, as it requires special config to make it vulnerable (custom appender config). If you flag log4j 1.x, you also need to flag any other code that can optionally make JNDI connections.

The problem is only log4j2, which in its default configuration reacts to `${jndi:...}`

**Comment by theonlykernel** [comment]
@uschindler well said and agreed. 

@hillu any chance we could have the flag added?

**Comment by hillu** [comment]
Sure. Would yyou like to do a pull request?

**Comment by hillu** [comment]
PR is there (#14) but it needs a bit of refinement.

**Comment by uschindler** [comment]
Thanks. Naming of parameter is a bit strange, maybe `--no-v1` would habe been better.
