### ISSUE TITLE
Even with exclude, tool scans folders

### ISSUE THREAD

**Issue by GElkayam** [hillu/local-log4j-vuln-scanner#42]
Issue is that the walking of the root includes mounted drives, which causes it to walk very large filesystems, and this caused OOM on our servers.

**Comment by hillu** [comment]
I don't get how walking large filesystems would lead to an OOM condition, but setting that issue aside for a moment… I have just tested and verified that the "-exclude" switch works fine, both with absolute and relative directories, at least on Linux systems.

**Comment by leepfrog-ger** [comment]
I noticed this too, I the `--exclude` paths that are specified are case sensitive.
This is unusual behavior (from a user perspective) because for windows file systems are generally case insensitive.

See example below:

```
tree /F C:\temp\log4j\findme\
Folder PATH listing for volume OS
Volume serial number is XXX
C:\temp\log4j\findme
├───excluded
│       log4j-1.2.17.jar
│
└───included
        log4j-1.2.17.jar
```

Running `.\local-log4j-vuln-scanner.exe --exclude C:\temp\log4j\findme\Excluded C:\temp\log4j\findme\` (notice capital E in excluded) yields:

```
indicator for vulnerable component found in C:\temp\log4j\findme\excluded\log4j-1.2.17.jar (org/apache/log4j/net/SocketNode.class): log4j 1.2.17
indicator for vulnerable component found in C:\temp\log4j\findme\included\log4j-1.2.17.jar (org/apache/log4j/net/SocketNode.class): log4j 1.2.17
```

Running `.\local-log4j-vuln-scanner.exe --exclude C:\temp\log4j\findme\excluded C:\temp\log4j\findme\` yields (this is the expected result):

```
indicator for vulnerable component found in C:\temp\log4j\findme\included\log4j-1.2.17.jar (org/apache/log4j/net/SocketNode.class): log4j 1.2.17
```

From a windows users perspective both commands should produce the same output (only one file found)

**Comment by hillu** [comment]
> I noticed this too, I think the `--exclude` paths that are specified are case sensitive.

Uh. I guess we could just document that behavior.

**Comment by GElkayam** [comment]
Sorry for the late comment, in my case it was trailing slash that caused the folder not to be excluded.
the use case was using glusterFS with 90TB of data, so it overrun the system.
