### ISSUE TITLE
Virustotal 2 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by isleeps** [hillu/local-log4j-vuln-scanner#60]
Are they false positives?
https://www.virustotal.com/gui/file/6e472463ae43279ea09bfa4aac8d6d2a544104fde83e2e4bb52808f6aae761a2?nocache=1
Got the file from oldgamesdownload.com

**Comment by hillu** [comment]
yes, they are FPs. I never heard of those products (SecureAge, Trapmine) before. My best guess is that they use static signatures that match on bits of the Go standard library. This has happened before (hello Microsoft!).

I'm going to close this issue because I don't see what I can do against AV vendors' systemic mistakes.
